table Axis
	lineageTag: 82ced111-777d-4fbb-98fb-0a7fe3731324

	measure 'Axis Value' = SELECTEDVALUE('Axis'[Axis])
		formatString: 0
		lineageTag: daf2c1ce-da49-4edc-bc3b-9331f0799dfd

	measure 'Axis Max' = MAX('Axis'[Axis])
		formatString: 0
		lineageTag: adcc5eea-3bf6-468a-9db2-82ce40a1aca4

	measure 'Axis Min' = Min('Axis'[Axis])
		formatString: 0
		lineageTag: 4ecb671d-4343-48c1-a233-f92548c144ec

	column Axis
		formatString: 0
		lineageTag: 71dc9288-ca32-41fd-81b2-7076dd44b866
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition Axis-a7cf5333-7910-4e78-9c51-3e3460c8b3e5 = calculated
		mode: import
		source = GENERATESERIES(0, 6000, 10)

	annotation PBI_Id = d0a97fb0afca4ade86cd49bd378b1ea4

